In [2]:
import torch
import torch.nn as nn
import numpy as np
import time
device = 'cude' if torch.cuda.is_available() else 'cpu'
print(device)

cpu


In [3]:
%%time
start_time = time.time()
# matrix operations here
zeros = torch.zeros(1, 1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.10f}")

0.0022270679
CPU times: user 408 µs, sys: 1.24 ms, total: 1.64 ms
Wall time: 2.29 ms


In [4]:
torch_rand1 = torch.rand(100, 100, 100, 100).to(device)
torch_rand2 = torch.rand(100, 100, 100, 100).to(device)
np_rand1 = torch.rand(100, 100, 100, 100)
np_rand2 = torch.rand(100, 100, 100, 100)

start_time = time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

start_time = time.time()

rand = np.multiply(np_rand1, np_rand2)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")





0.21004701
0.32520604


In [5]:
# torch.stack, torch.multinomial, torch.tril, torch.triu, input.transpose, nn.linear, torch.cat, F.softmax (show all the examples of functions/methods with pytorch docs)

# Define a probability tensor
probabilities = torch.tensor([0.1, 0.9])
# 10% or 0.1 => 0, 90% or 0.9 => 1 each probability points to the index of the probability in the tensor
# draw 5 samples form the multinomial distribution 
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
print(samples)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


In [6]:
tensor = torch.tensor([1, 2, 3, 4])
out = torch.cat((tensor, torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5])

In [7]:
out = torch.tril(torch.ones(5, 5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [8]:
out = torch.triu(torch.ones(5, 5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [9]:
out = torch.zeros(5, 5).masked_fill(torch.tril(torch.ones(5, 5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [10]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [11]:
input = torch.zeros(2, 3, 4)
out = input.transpose(0, 2)
out.shape

torch.Size([4, 3, 2])

In [12]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
tensor3 = torch.tensor([7, 8, 9])

# Stack the tensors along a new dimension
stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [13]:
import torch.nn as nn
sample = torch.tensor([10., 10., 10.])
linear = nn.Linear(3, 3, bias=False)
print(linear(sample))

tensor([ 1.4721, -4.4892, -6.2241], grad_fn=<SqueezeBackward4>)


In [14]:
import torch.nn.functional as F

# Create a tensor 
tensor1 = torch.tensor([1.0, 2.0, 3.0])

# Apply softmax using torch.nn.functional.softmax()
softmax_output = F.softmax(tensor1, dim=0)

print(softmax_output)


tensor([0.0900, 0.2447, 0.6652])


In [18]:
# Initialize an embedding Layer
vocab_size = 100 
embedding_dim = 6
embedding = nn.Embedding(vocab_size, embedding_dim)

# Create some input indices
input_indices = torch.LongTensor([1, 5, 3, 2])

# Apply the embedding Layer
embedded_output = embedding(input_indices)

# The output will be a tensor of shape (4, 100) where 4 is the number of inputs
# and 100 is the dimensionality of the embedding vectors
print(embedded_output.shape)
print(embedded_output)

torch.Size([4, 6])
tensor([[ 0.1683,  1.3465, -0.3101, -0.6164,  2.6972,  0.4243],
        [-1.1730,  0.4521, -1.2227, -0.8757,  0.3028, -1.2165],
        [-1.1787,  0.4837, -0.4610, -0.5864, -1.4333,  0.5857],
        [ 0.5381, -1.4124,  0.5670,  1.6694, -0.0949,  1.0274]],
       grad_fn=<EmbeddingBackward0>)


In [24]:
a = torch.tensor([[1,2],[3,4],[5,6]])
b = torch.tensor([[7,8,9],[10,11,12]])
# print(a @ b)
print(torch.matmul(a, b))

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [20]:
int_64 = torch.randint(1, (3,2), dtype=torch.float32)
#type int64
float_32 = torch.rand(2,3, dtype=torch.float32)
#type float32
result = torch.matmul(int_64, float_32)
print(result)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [21]:
a = torch.rand(2, 3, 5)
print(a.shape)
x, y, z = a.shape
a = a.view(x,y,z)
print(x, y, z)
print(a.shape)

torch.Size([2, 3, 5])
2 3 5
torch.Size([2, 3, 5])


In [22]:
input = torch.rand((4, 8, 10))
B, T, C = input.shape
output = input.view(B * T, C)
print(output)
#print(input)
print(output[:, -1])

tensor([[0.6411, 0.6509, 0.8336, 0.3491, 0.7207, 0.7003, 0.1516, 0.5727, 0.0478,
         0.7273],
        [0.3100, 0.7997, 0.1067, 0.3455, 0.6970, 0.9209, 0.3366, 0.7663, 0.1893,
         0.7188],
        [0.6143, 0.9458, 0.3171, 0.3064, 0.2634, 0.9249, 0.0839, 0.1801, 0.1697,
         0.8168],
        [0.6933, 0.0960, 0.6545, 0.6990, 0.4372, 0.5539, 0.4034, 0.1940, 0.1965,
         0.6795],
        [0.4204, 0.9668, 0.6614, 0.6326, 0.7671, 0.7319, 0.8047, 0.1688, 0.4421,
         0.8839],
        [0.7112, 0.7013, 0.0362, 0.6571, 0.8430, 0.5649, 0.2659, 0.2621, 0.6256,
         0.8865],
        [0.4177, 0.9753, 0.3165, 0.2545, 0.2723, 0.9203, 0.8246, 0.5518, 0.4800,
         0.0084],
        [0.8408, 0.7374, 0.3527, 0.4497, 0.9075, 0.1346, 0.6716, 0.6748, 0.1282,
         0.0535],
        [0.1964, 0.7296, 0.1714, 0.7866, 0.6607, 0.0251, 0.5071, 0.0827, 0.9227,
         0.2310],
        [0.5004, 0.5148, 0.6301, 0.3064, 0.0588, 0.7316, 0.6616, 0.4871, 0.1462,
         0.5565],
        [0

In [23]:
x = torch.tensor([-0.05], dtype=torch.float32)
y = torch.tanh(x)
print(y)

tensor([-0.0500])
